name: Standalone Operations

on:
    push:
        branches:
            - main

jobs:
    run_pull:
        name: run pull 
        runs-on: ubuntu-latest

        steps:
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

        - name: Enviar variable al servidor
          run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'export API_TOKEN=${{ secrets.HF_TOKEN }}' >> ~/.bashrc"

        - name: connect and pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"

        # - name: Killer bash
        #   run: |
        #       set -x
        #       ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && chmod +x killer.sh && ./killer.sh"

        # - name: Launch Gradio Server
        #   run: |
        #       set -x
        #       ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -tt "cd ${{ secrets.WORK_DIR }} && chmod +x launcher.sh && ./launcher.sh"
        
        # - name: stop running gradio app
        #   run: |
        #       ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pkill python"      

        # - name: activate enviroment and run 
        #   run: |
        #       ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && source venv/bin/activate && python app.py \& && exit"      
                
        - name: cleanup
          run: rm -rf ~/.ssh
